---
# Source: authelia/templates/networkPolicy.yaml
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: authelia
  namespace: authelia
  labels: 
    app.kubernetes.io/name: authelia
    app.kubernetes.io/instance: authelia
    app.kubernetes.io/version: 4.39.24
    app.kubernetes.io/managed-by: Helm
    helm.sh/chart: authelia-0.11.22
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/name: authelia
      app.kubernetes.io/instance: authelia
  policyTypes:
  - Ingress
  - Egress
  ingress: 
    - from:
      - namespaceSelector:
          matchLabels:
            kubernetes.io/metadata.name: ingress-nginx
      ports:
      - port: 9091
        protocol: TCP
  egress:
    - ports:
      - port: 53
        protocol: UDP
      - port: 53
        protocol: TCP
      to:
      - namespaceSelector:
          matchLabels:
            kubernetes.io/metadata.name: kube-system
---
# Source: authelia/templates/configMap.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: authelia
  namespace: authelia
  labels: 
    app.kubernetes.io/name: authelia
    app.kubernetes.io/instance: authelia
    app.kubernetes.io/version: 4.39.24
    app.kubernetes.io/managed-by: Helm
    helm.sh/chart: authelia-0.11.22
data:
  configuration.yaml: |
    ---
    # yaml-language-server: $schema=https://www.authelia.com/schemas/v4.39/json-schema/configuration.json
    theme: 'auto'
    default_2fa_method: 'totp'
    server:
      address: 'tcp://0.0.0.0:9091/'
      asset_path: ''
      headers:
        csp_template: ""
      buffers:
        read: 4096
        write: 4096
      timeouts:
        read: '6 seconds'
        write: '6 seconds'
        idle: '30 seconds'
      endpoints:
        enable_pprof: false
        enable_expvars: false
        authz:
          auth-request:
            implementation: 'AuthRequest'
        rate_limits:
          reset_password_start:
            enable: true
          reset_password_finish:
            enable: true
          second_factor_totp:
            enable: true
          second_factor_duo:
            enable: true
          session_elevation_start:
            enable: true
          session_elevation_finish:
            enable: true
          openid_connect_token:
            enable: true
          openid_connect_pushed_authorization_request:
            enable: true
          openid_connect_userinfo:
            enable: true
          openid_connect_introspection:
            enable: true
          openid_connect_revocation:
            enable: true
          second_factor_password:
            enable: true
    log:
      level: 'info'
      format: 'json'
      file_path: ''
      keep_stdout: true
    telemetry:
      metrics:
        enabled: false
    identity_validation:
      elevated_session:
        code_lifespan: '5 minutes'
        elevation_lifespan: '10 minutes'
        characters: 8
        require_second_factor: false
        skip_second_factor: false
      reset_password:
        jwt_lifespan: '5 minutes'
        jwt_algorithm: 'HS256'
    totp:
      disable: false
      issuer: 'SRE Platform'
      skew: 1
      secret_size: 32
      algorithm: 'SHA1'
      digits: 6
      period: 30
      disable_reuse_security_policy: false
      allowed_algorithms:
        - 'SHA1'
      allowed_digits:
        - 6
      allowed_periods:
        - 30
    webauthn:
      disable: false
      enable_passkey_login: false
      experimental_enable_passkey_uv_two_factors: false
      experimental_enable_passkey_upgrade: false
      display_name: 'Authelia'
      attestation_conveyance_preference: 'indirect'
      timeout: '60 seconds'
      filtering:
        permitted_aaguids: []
        prohibited_aaguids: []
        prohibit_backup_eligibility: false
      selection_criteria:
        attachment: ''
        discoverability: 'preferred'
        user_verification: 'preferred'
      metadata:
        enabled: false
        cache_policy: 'strict'
        validate_trust_anchor: true
        validate_entry: true
        validate_entry_permit_zero_aaguid: false
        validate_status: true
        validate_status_permitted: []
        validate_status_prohibited: []
    ntp:
      address: 'udp://time.cloudflare.com:123'
      version: 4
      max_desync: '3 seconds'
      disable_startup_check: true
      disable_failure: true
    authentication_backend:
      password_reset:
        disable: true
        custom_url: ''
      password_change:
        disable: false
      refresh_interval: '5 minutes'
      file:
        path: '/config/authelia/users/users_database.yml'
        watch: true
        search:
          email: false
          case_insensitive: false
        password:
          algorithm: 'argon2'
          argon2:
            variant: 'argon2id'
            iterations: 3
            memory: 65536
            parallelism: 2
            key_length: 32
            salt_length: 16
          scrypt:
            variant: 'scrypt'
            iterations: 16
            block_size: 8
            parallelism: 1
            key_length: 32
            salt_length: 16
          pbkdf2:
            variant: 'sha512'
            iterations: 310000
            salt_length: 16
          sha2crypt:
            variant: 'sha512'
            iterations: 50000
            salt_length: 16
          bcrypt:
            variant: 'standard'
            cost: 12
    password_policy:
      standard:
        enabled: false
        min_length: 8
        max_length: 0
        require_uppercase: false
        require_lowercase: false
        require_number: false
        require_special: false
      zxcvbn:
        enabled: false
        min_score: 0
    session:
      name: 'authelia_session'
      same_site: 'lax'
      inactivity: '15 minutes'
      expiration: '1 hour'
      remember_me: '8 hours'
      cookies:
        - domain: '139.162.145.158.nip.io'
          authelia_url: 'https://auth.139.162.145.158.nip.io'
          default_redirection_url: 'https://headlamp.139.162.145.158.nip.io'
    regulation:
      modes:
      - 'user'
      max_retries: 3
      find_time: '2 minutes'
      ban_time: '5 minutes'
    storage:
      local:
        path: '/config/db.sqlite3'
    notifier:
      disable_startup_check: false
      filesystem:
        filename: '/config/notification.txt'
    access_control:
      default_policy: 'deny'
      rules:
        - policy: two_factor
          domain:
            - 'headlamp.139.162.145.158.nip.io'
    ...
---
# Source: authelia/templates/persistentVolumeClaim.yaml
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: authelia
  namespace: authelia
  labels: 
    app.kubernetes.io/name: authelia
    app.kubernetes.io/instance: authelia
    app.kubernetes.io/version: 4.39.24
    app.kubernetes.io/managed-by: Helm
    helm.sh/chart: authelia-0.11.22
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
# Source: authelia/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: authelia
  namespace: authelia
  labels: 
    app.kubernetes.io/name: authelia
    app.kubernetes.io/instance: authelia
    app.kubernetes.io/version: 4.39.24
    app.kubernetes.io/managed-by: Helm
    helm.sh/chart: authelia-0.11.22
spec:
  type: ClusterIP
  sessionAffinity: None
  selector:
    app.kubernetes.io/name: authelia
    app.kubernetes.io/instance: authelia
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: http
---
# Source: authelia/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: authelia
  namespace: authelia
  labels: 
    app.kubernetes.io/name: authelia
    app.kubernetes.io/instance: authelia
    app.kubernetes.io/version: 4.39.24
    app.kubernetes.io/managed-by: Helm
    helm.sh/chart: authelia-0.11.22
spec:
  selector:
    matchLabels: 
      app.kubernetes.io/name: authelia
      app.kubernetes.io/instance: authelia
  revisionHistoryLimit: 5
  replicas: 1
  minReadySeconds: 0
  strategy:
    type: RollingUpdate
    rollingUpdate: 
      maxSurge: 25%
      maxUnavailable: 25%
  template:
    metadata:
      labels: 
        app.kubernetes.io/name: authelia
        app.kubernetes.io/instance: authelia
        app.kubernetes.io/version: 4.39.24
        app.kubernetes.io/managed-by: Helm
        helm.sh/chart: authelia-0.11.22
      annotations:
        authelia.com/checksum-config: 33f05cd330d4f962d5b5144de9a8eeb887b14c4c5f4565270caa9fa70b87e783
        
    spec:
      hostNetwork: false
      hostPID: false
      hostIPC: false
      affinity: 
        nodeAffinity: {}
        podAffinity: {}
        podAntiAffinity: {}
      securityContext: 
        fsGroup: 1000
        runAsGroup: 1000
        runAsNonRoot: true
        runAsUser: 1000
        seccompProfile:
          type: RuntimeDefault
      enableServiceLinks: false
      containers:
      - name: authelia
        image: ghcr.io/authelia/authelia:4.39.24
        imagePullPolicy: IfNotPresent
        command:
        - 'authelia'
        resources: 
          limits:
            cpu: 500m
            memory: 512Mi
          requests:
            cpu: 100m
            memory: 128Mi
        env:
        - name: AUTHELIA_SERVER_DISABLE_HEALTHCHECK
          value: "true"
        - name: AUTHELIA_IDENTITY_VALIDATION_RESET_PASSWORD_JWT_SECRET_FILE
          value: '/secrets/internal/identity_validation.reset_password.jwt.hmac.key'
        - name: AUTHELIA_SESSION_SECRET_FILE
          value: '/secrets/internal/session.encryption.key'
        - name: AUTHELIA_STORAGE_ENCRYPTION_KEY_FILE
          value: '/secrets/internal/storage.encryption.key'
        - name: X_AUTHELIA_CONFIG
          value: '/configuration.yaml'
        - name: X_AUTHELIA_CONFIG_FILTERS
          value: template
        startupProbe:
          failureThreshold: 6
          httpGet:
            path: /api/health
            port: http
            scheme: HTTP
          initialDelaySeconds: 10
          periodSeconds: 5
          successThreshold: 1
          timeoutSeconds: 5
        livenessProbe:
          failureThreshold: 5
          httpGet:
            path: /api/health
            port: http
            scheme: HTTP
          initialDelaySeconds: 0
          periodSeconds: 30
          successThreshold: 1
          timeoutSeconds: 5
        readinessProbe:
          failureThreshold: 5
          httpGet:
            path: /api/health
            port: http
            scheme: HTTP
          initialDelaySeconds: 0
          periodSeconds: 5
          successThreshold: 1
          timeoutSeconds: 5
        ports:
        - name: http
          containerPort: 9091
          protocol: TCP
        volumeMounts:
        - name: authelia
          mountPath: /config
          readOnly: false
        - name: config
          mountPath: /configuration.yaml
          subPath: configuration.yaml
          readOnly: true
        - name: secrets
          mountPath: /secrets/internal
          readOnly: true
        - mountPath: /config/authelia/users
          name: users-database
          readOnly: true
        securityContext: 
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
          readOnlyRootFilesystem: true
          runAsGroup: 1000
          runAsNonRoot: true
          runAsUser: 1000
      volumes:
      - name: authelia
        persistentVolumeClaim:
          claimName: authelia
      - name: config
        configMap:
          name: authelia
          items:
          - key: configuration.yaml
            path: configuration.yaml
      - name: secrets
        secret:
          secretName: authelia-secrets
          items:
          - key: identity_validation.reset_password.jwt.hmac.key
            path: identity_validation.reset_password.jwt.hmac.key
          - key: session.encryption.key
            path: session.encryption.key
          - key: storage.encryption.key
            path: storage.encryption.key
      - name: users-database
        secret:
          secretName: authelia-users
---
# Source: authelia/templates/ingress.yaml
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: authelia
  namespace: authelia
  labels: 
    app.kubernetes.io/name: authelia
    app.kubernetes.io/instance: authelia
    app.kubernetes.io/version: 4.39.24
    app.kubernetes.io/managed-by: Helm
    helm.sh/chart: authelia-0.11.22
  annotations: 
    cert-manager.io/cluster-issuer: sre-tools-letsencrypt
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
spec:
  ingressClassName: nginx
  rules:
  - host: 'auth.139.162.145.158.nip.io'
    http:
      paths:
        - path: '/'
          pathType: Prefix
          backend:
            service:
              name: authelia
              port:
                number: 80
  tls:
    - hosts:
        - 'auth.139.162.145.158.nip.io'
      secretName: authelia-tls
---
# Source: authelia/templates/extraObjects.yaml
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  labels:
    app.kubernetes.io/managed-by: srectl
    app.kubernetes.io/part-of: sre-platform
  name: sre-tools-letsencrypt
spec:
  acme:
    privateKeySecretRef:
      name: sre-tools-letsencrypt-account
    server: https://acme-v02.api.letsencrypt.org/directory
    solvers:
    - http01:
        ingress:
          ingressClassName: nginx
