---
# Source: openbao/templates/server-disruptionbudget.yaml
# PodDisruptionBudget to prevent degrading the server cluster through
# voluntary cluster changes.
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: bao-prod-openbao
  namespace: openbao-prod
  labels:
    helm.sh/chart: openbao-0.28.4
    app.kubernetes.io/name: openbao
    app.kubernetes.io/instance: bao-prod
    app.kubernetes.io/managed-by: Helm
spec:
  maxUnavailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: openbao
      app.kubernetes.io/instance: bao-prod
      component: server
---
# Source: openbao/templates/server-serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: bao-prod-openbao
  namespace: openbao-prod
  labels:
    helm.sh/chart: openbao-0.28.4
    app.kubernetes.io/name: openbao
    app.kubernetes.io/instance: bao-prod
    app.kubernetes.io/managed-by: Helm
---
# Source: openbao/templates/server-config-configmap.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: bao-prod-openbao-config
  namespace: openbao-prod
  labels:
    helm.sh/chart: openbao-0.28.4
    app.kubernetes.io/name: openbao
    app.kubernetes.io/instance: bao-prod
    app.kubernetes.io/managed-by: Helm
data:
  extraconfig-from-values.hcl: |-
    
    ui = true
    
    listener "tcp" {
      tls_disable     = 0
      tls_cert_file   = "/tls/tls.crt"
      tls_key_file    = "/tls/tls.key"
    	  tls_disable_client_certs = true
      address         = "[::]:8200"
      cluster_address = "[::]:8201"
      telemetry {
        unauthenticated_metrics_access = false
      }
    }
    
    storage "raft" {
      path = "/openbao/data"
    }
    
    service_registration "kubernetes" {}
---
# Source: openbao/templates/server-clusterrolebinding.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: bao-prod-openbao-server-binding
  labels:
    helm.sh/chart: openbao-0.28.4
    app.kubernetes.io/name: openbao
    app.kubernetes.io/instance: bao-prod
    app.kubernetes.io/managed-by: Helm
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: system:auth-delegator
subjects:
- kind: ServiceAccount
  name: bao-prod-openbao
  namespace: openbao-prod
---
# Source: openbao/templates/server-discovery-role.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: openbao-prod
  name: bao-prod-openbao-discovery-role
  labels:
    helm.sh/chart: openbao-0.28.4
    app.kubernetes.io/name: openbao
    app.kubernetes.io/instance: bao-prod
    app.kubernetes.io/managed-by: Helm
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "watch", "list", "update", "patch"]
---
# Source: openbao/templates/server-discovery-rolebinding.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: bao-prod-openbao-discovery-rolebinding
  namespace: openbao-prod
  labels:
    helm.sh/chart: openbao-0.28.4
    app.kubernetes.io/name: openbao
    app.kubernetes.io/instance: bao-prod
    app.kubernetes.io/managed-by: Helm
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: bao-prod-openbao-discovery-role
subjects:
- kind: ServiceAccount
  name: bao-prod-openbao
  namespace: openbao-prod
---
# Source: openbao/templates/server-ha-active-service.yaml
# Service for active OpenBao pod
apiVersion: v1
kind: Service
metadata:
  name: bao-prod-openbao-active
  namespace: openbao-prod
  labels:
    helm.sh/chart: openbao-0.28.4
    app.kubernetes.io/name: openbao
    app.kubernetes.io/instance: bao-prod
    app.kubernetes.io/managed-by: Helm
    openbao-active: "true"
spec:
  type: ClusterIP
  publishNotReadyAddresses: true
  ports:
    - name: https
      port: 8200
      targetPort: 8200
      appProtocol: HTTPS
    - name: https-internal
      port: 8201
      targetPort: 8201
  selector:
    app.kubernetes.io/name: openbao
    app.kubernetes.io/instance: bao-prod
    component: server
    openbao-active: "true"
---
# Source: openbao/templates/server-ha-standby-service.yaml
# Service for standby OpenBao pod
apiVersion: v1
kind: Service
metadata:
  name: bao-prod-openbao-standby
  namespace: openbao-prod
  labels:
    helm.sh/chart: openbao-0.28.4
    app.kubernetes.io/name: openbao
    app.kubernetes.io/instance: bao-prod
    app.kubernetes.io/managed-by: Helm
spec:
  type: ClusterIP
  publishNotReadyAddresses: true
  ports:
    - name: https
      port: 8200
      targetPort: 8200
      appProtocol: HTTPS
    - name: https-internal
      port: 8201
      targetPort: 8201
  selector:
    app.kubernetes.io/name: openbao
    app.kubernetes.io/instance: bao-prod
    component: server
    openbao-active: "false"
---
# Source: openbao/templates/server-headless-service.yaml
# Service for OpenBao cluster
apiVersion: v1
kind: Service
metadata:
  name: bao-prod-openbao-internal
  namespace: openbao-prod
  labels:
    helm.sh/chart: openbao-0.28.4
    app.kubernetes.io/name: openbao
    app.kubernetes.io/instance: bao-prod
    app.kubernetes.io/managed-by: Helm
    openbao-internal: "true"
spec:
  clusterIP: None
  publishNotReadyAddresses: true
  ports:
    - name: "https"
      port: 8200
      targetPort: 8200
      appProtocol: HTTPS
    - name: https-internal
      port: 8201
      targetPort: 8201
  selector:
    app.kubernetes.io/name: openbao
    app.kubernetes.io/instance: bao-prod
    component: server
---
# Source: openbao/templates/server-service.yaml
# Service for OpenBao cluster
apiVersion: v1
kind: Service
metadata:
  name: bao-prod-openbao
  namespace: openbao-prod
  labels:
    helm.sh/chart: openbao-0.28.4
    app.kubernetes.io/name: openbao
    app.kubernetes.io/instance: bao-prod
    app.kubernetes.io/managed-by: Helm
spec:
  type: ClusterIP
  # We want the servers to become available even if they're not ready
  # since this DNS is also used for join operations.
  publishNotReadyAddresses: true
  ports:
    - name: https
      port: 8200
      targetPort: 8200
      appProtocol: HTTPS
    - name: https-internal
      port: 8201
      targetPort: 8201
  selector:
    app.kubernetes.io/name: openbao
    app.kubernetes.io/instance: bao-prod
    component: server
---
# Source: openbao/templates/server-statefulset.yaml
# StatefulSet to run the actual openbao server cluster.
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: bao-prod-openbao
  namespace: openbao-prod
  labels:
    app.kubernetes.io/name: openbao
    app.kubernetes.io/instance: bao-prod
    app.kubernetes.io/managed-by: Helm
spec:
  serviceName: bao-prod-openbao-internal
  podManagementPolicy: OrderedReady
  replicas: 3
  updateStrategy:
    type: OnDelete
  selector:
    matchLabels:
      app.kubernetes.io/name: openbao
      app.kubernetes.io/instance: bao-prod
      component: server
  template:
    metadata:
      labels:
        helm.sh/chart: openbao-0.28.4
        app.kubernetes.io/name: openbao
        app.kubernetes.io/instance: bao-prod
        component: server
    spec:
      
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchLabels:
                  app.kubernetes.io/name: openbao
                  app.kubernetes.io/instance: "bao-prod"
                  component: server
              topologyKey: kubernetes.io/hostname
  
      
      
      
      terminationGracePeriodSeconds: 10
      serviceAccountName: bao-prod-openbao
      
      securityContext:
        seccompProfile:
          type: RuntimeDefault
        runAsNonRoot: true
        runAsGroup: 1000
        runAsUser: 100
        fsGroup: 1000
      hostNetwork: false
      volumes:
        
        - name: config
          configMap:
            name: bao-prod-openbao-config
  
        - name: openbao-tls
          secret:
            secretName: openbao-server-tls
        - name: home
          emptyDir: {}
      containers:
        - name: openbao
          resources:
            limits:
              cpu: 1000m
              memory: 1Gi
            requests:
              cpu: 250m
              memory: 512Mi
  
          image: "quay.io/openbao/openbao:2.5.5"
          imagePullPolicy: IfNotPresent
          command:
          - "/bin/sh"
          - "-ec"
          args: 
          - |
            cp /openbao/config/extraconfig-from-values.hcl /tmp/storageconfig.hcl;
            [ -n "${HOST_IP}" ] && sed -Ei "s|HOST_IP|${HOST_IP?}|g" /tmp/storageconfig.hcl;
            [ -n "${POD_IP}" ] && sed -Ei "s|POD_IP|${POD_IP?}|g" /tmp/storageconfig.hcl;
            [ -n "${HOSTNAME}" ] && sed -Ei "s|HOSTNAME|${HOSTNAME?}|g" /tmp/storageconfig.hcl;
            [ -n "${API_ADDR}" ] && sed -Ei "s|API_ADDR|${API_ADDR?}|g" /tmp/storageconfig.hcl;
            [ -n "${TRANSIT_ADDR}" ] && sed -Ei "s|TRANSIT_ADDR|${TRANSIT_ADDR?}|g" /tmp/storageconfig.hcl;
            [ -n "${RAFT_ADDR}" ] && sed -Ei "s|RAFT_ADDR|${RAFT_ADDR?}|g" /tmp/storageconfig.hcl;
            /usr/local/bin/docker-entrypoint.sh bao server -config=/tmp/storageconfig.hcl 
   
          securityContext:
            allowPrivilegeEscalation: false
          env:
            - name: HOST_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.hostIP
            - name: POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            - name: BAO_K8S_POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: BAO_K8S_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: BAO_ADDR
              value: "https://127.0.0.1:8200"
            - name: BAO_API_ADDR
              value: "https://$(POD_IP):8200"
            - name: SKIP_CHOWN
              value: "true"
            - name: SKIP_SETCAP
              value: "true"
            - name: HOSTNAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: BAO_CLUSTER_ADDR
              value: "https://$(HOSTNAME).bao-prod-openbao-internal:8201"
            - name: BAO_RAFT_NODE_ID
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: HOME
              value: "/home/openbao"
            
            
            
            - name: "OPENBAO_ADDR"
              value: "https://127.0.0.1:8200"
          volumeMounts:
          
            - name: audit
              mountPath: /openbao/audit
  
  
    
            - name: data
              mountPath: /openbao/data
    
  
  
            - name: config
              mountPath: /openbao/config
  
            - mountPath: /tls
              name: openbao-tls
              readOnly: true
            - name: home
              mountPath: /home/openbao
          ports:
            - containerPort: 8200
              name: https
            - containerPort: 8201
              name: https-internal
            - containerPort: 8202
              name: https-rep
          readinessProbe:
            # Check status; unsealed openbao servers return 0
            # The exit code reflects the seal status:
            #   0 - unsealed
            #   1 - error
            #   2 - sealed
            exec:
              command: ["/bin/sh", "-ec", "bao status -tls-skip-verify"]
            failureThreshold: 2
            initialDelaySeconds: 5
            periodSeconds: 5
            successThreshold: 1
            timeoutSeconds: 3
          lifecycle:
            # openbao container doesn't receive SIGTERM from Kubernetes
            # and after the grace period ends, Kube sends SIGKILL.  This
            # causes issues with graceful shutdowns such as deregistering itself
            # from Consul (zombie services).
            preStop:
              exec:
                command: [
                  "/bin/sh", "-c",
                  # Adding a sleep here to give the pod eviction a
                  # chance to propagate, so requests will not be made
                  # to this pod while it's terminating
                  "sleep 5 && kill -SIGTERM $(pidof bao)",
                ]
      
  
  volumeClaimTemplates:
    - apiVersion: v1
      kind: PersistentVolumeClaim
      metadata:
        name: data
      
      
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 20Gi
        storageClassName: linode-block-storage-retain
      
    - apiVersion: v1
      kind: PersistentVolumeClaim
      metadata:
        name: audit
      
      
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 10Gi
        storageClassName: linode-block-storage-retain
---
# Source: openbao/templates/tests/server-test.yaml
apiVersion: v1
kind: Pod
metadata:
  name: bao-prod-openbao-server-test
  namespace: openbao-prod
  annotations:
    "helm.sh/hook": test
spec:
  
  containers:
    - name: bao-prod-server-test
      image: quay.io/openbao/openbao:2.5.5
      imagePullPolicy: IfNotPresent
      env:
        - name: VAULT_ADDR
          value: https://bao-prod-openbao.openbao-prod.svc:8200
        
        - name: "OPENBAO_ADDR"
          value: "https://127.0.0.1:8200"
      command:
        - /bin/sh
        - -c
        - |
          echo "Checking for sealed info in 'bao status' output"
          ATTEMPTS=10
          n=0
          until [ "$n" -ge $ATTEMPTS ]
          do
            echo "Attempt" $n...
            bao status -format yaml | grep -E '^sealed: (true|false)' && break
            n=$((n+1))
            sleep 5
          done
          if [ $n -ge $ATTEMPTS ]; then
            echo "timed out looking for sealed info in 'bao status' output"
            exit 1
          fi

          exit 0
      volumeMounts:
        - mountPath: /tls
          name: openbao-tls
          readOnly: true
  volumes:
    - name: openbao-tls
      secret:
        secretName: openbao-server-tls
  restartPolicy: Never

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: openbao-auth-delegator
  labels:
    app.kubernetes.io/part-of: sre-platform
    app.kubernetes.io/managed-by: srectl
    app.kubernetes.io/component: openbao-rbac
subjects:
- kind: ServiceAccount
  name: openbao
  namespace: openbao-prod
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: system:auth-delegator
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: default-deny
  namespace: openbao-prod
  labels:
    app.kubernetes.io/part-of: sre-platform
    app.kubernetes.io/managed-by: srectl
    app.kubernetes.io/component: openbao-network
spec:
  podSelector: {}
  policyTypes:
  - Ingress
  - Egress
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-raft-peer
  namespace: openbao-prod
  labels:
    app.kubernetes.io/part-of: sre-platform
    app.kubernetes.io/managed-by: srectl
    app.kubernetes.io/component: openbao-network
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/name: openbao
  policyTypes:
  - Ingress
  - Egress
  ingress:
  - from:
    - podSelector:
        matchLabels:
          app.kubernetes.io/name: openbao
    ports:
    - protocol: TCP
      port: 8201
  egress:
  - to:
    - podSelector:
        matchLabels:
          app.kubernetes.io/name: openbao
    ports:
    - protocol: TCP
      port: 8201
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-eso-ingress
  namespace: openbao-prod
  labels:
    app.kubernetes.io/part-of: sre-platform
    app.kubernetes.io/managed-by: srectl
    app.kubernetes.io/component: openbao-network
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/name: openbao
  policyTypes:
  - Ingress
  ingress:
  - from:
    - namespaceSelector:
        matchLabels:
          kubernetes.io/metadata.name: external-secrets
    ports:
    - protocol: TCP
      port: 8200
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-ingress-controller
  namespace: openbao-prod
  labels:
    app.kubernetes.io/part-of: sre-platform
    app.kubernetes.io/managed-by: srectl
    app.kubernetes.io/component: openbao-network
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/name: openbao
  policyTypes:
  - Ingress
  ingress:
  - from:
    - namespaceSelector:
        matchLabels:
          kubernetes.io/metadata.name: ingress-nginx
    ports:
    - protocol: TCP
      port: 8200
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-acme-http01-solver
  namespace: openbao-prod
  labels:
    app.kubernetes.io/part-of: sre-platform
    app.kubernetes.io/managed-by: srectl
    app.kubernetes.io/component: openbao-network
spec:
  podSelector:
    matchLabels:
      acme.cert-manager.io/http01-solver: "true"
  policyTypes:
  - Ingress
  ingress:
  - from:
    - namespaceSelector:
        matchLabels:
          kubernetes.io/metadata.name: ingress-nginx
    ports:
    - protocol: TCP
      port: 8089
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-dns
  namespace: openbao-prod
  labels:
    app.kubernetes.io/part-of: sre-platform
    app.kubernetes.io/managed-by: srectl
    app.kubernetes.io/component: openbao-network
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/name: openbao
  policyTypes:
  - Egress
  egress:
  - to:
    - ipBlock:
        cidr: 10.128.0.10/32
    ports:
    - protocol: UDP
      port: 53
    - protocol: TCP
      port: 53
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-kubernetes-api
  namespace: openbao-prod
  labels:
    app.kubernetes.io/part-of: sre-platform
    app.kubernetes.io/managed-by: srectl
    app.kubernetes.io/component: openbao-network
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/name: openbao
  policyTypes:
  - Egress
  egress:
  - to:
    - ipBlock:
        cidr: 10.128.0.1/32
    ports:
    - protocol: TCP
      port: 443
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: openbao-server-tls
  namespace: openbao-prod
  labels:
    app.kubernetes.io/part-of: sre-platform
    app.kubernetes.io/managed-by: srectl
    app.kubernetes.io/component: openbao-tls
spec:
  secretName: openbao-server-tls
  issuerRef:
    name: openbao-internal-ca
    kind: Issuer
  dnsNames:
  - openbao.139.162.145.158.nip.io
  - bao-prod.openbao-prod.svc.cluster.local
  - "*.bao-prod-internal.openbao-prod.svc.cluster.local"
  duration: 8760h
  renewBefore: 720h
  privateKey:
    algorithm: ECDSA
    size: 256
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: openbao-api
  namespace: openbao-prod
  labels:
    app.kubernetes.io/part-of: sre-platform
    app.kubernetes.io/managed-by: srectl
    app.kubernetes.io/component: openbao-ingress
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
    cert-manager.io/issuer: letsencrypt-staging
spec:
  ingressClassName: nginx
  tls:
  - hosts:
    - openbao.139.162.145.158.nip.io
    secretName: openbao-api-tls
  rules:
  - host: openbao.139.162.145.158.nip.io
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: bao-prod-active
            port:
              number: 8200