apiVersion: v1
kind: Namespace
metadata:
  name: gatus
  labels:
    app.kubernetes.io/managed-by: srectl
    app.kubernetes.io/name: gatus
    app.kubernetes.io/part-of: sre-platform
    sre.platform.io/owner-module: gatus
    sre.platform.io/tenant: sre-tools
    pod-security.kubernetes.io/enforce: restricted
    pod-security.kubernetes.io/enforce-version: latest
    pod-security.kubernetes.io/audit: restricted
    pod-security.kubernetes.io/warn: restricted
