apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: external-secrets
  namespace: argocd
  annotations:
    argocd.argoproj.io/refresh: hard
  labels:
    app.kubernetes.io/part-of: sre-platform
    app.kubernetes.io/managed-by: srectl
    sre.platform.io/tenant: "dawid-local"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: platform
  source:
    repoURL: "https://github.com/dawid-koldras-home/sre-platform-gitops.git"
    targetRevision: "main"
    path: "platform/modules/external-secrets"
  destination:
    server: https://kubernetes.default.svc
    namespace: "external-secrets"
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
      - PrunePropagationPolicy=foreground
      - PruneLast=true
    retry:
      limit: 3
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
