apiVersion: v1
kind: Namespace
metadata:
  labels:
    app.kubernetes.io/component: observability
    app.kubernetes.io/name: clickstack
    app.kubernetes.io/part-of: sre-platform
    pod-security.kubernetes.io/audit: restricted
    pod-security.kubernetes.io/enforce: restricted
    pod-security.kubernetes.io/warn: restricted
  name: clickstack
